product:
  type: lib
  platforms: [jvm]

repositories:
  - https://maven.pkg.jetbrains.space/kotlin/p/kotlin/kotlin-dependencies
  - https://maven.pkg.jetbrains.space/kotlin/p/kotlin/bootstrap
  - https://packages.jetbrains.team/maven/p/ij/intellij-dependencies
  - https://www.jetbrains.com/intellij-repository/releases
  - https://download.jetbrains.com/teamcity-repository


dependencies:
  - com.google.guava:guava:33.3.1-jre
  - org.jetbrains.kotlin:kotlin-reflect:1.6.10
  - com.jetbrains.intellij.platform:util:233.13135.128
  - com.jetbrains.intellij.platform:util-rt:233.13135.128
  - com.jetbrains.intellij.platform:util-class-loader:233.13135.128
  - com.jetbrains.intellij.platform:util-base:233.13135.128
  - com.jetbrains.intellij.platform:util-xml-dom:233.13135.128
  - com.jetbrains.intellij.platform:core:233.13135.128
  - com.jetbrains.intellij.platform:core-impl:233.13135.128
  - com.jetbrains.intellij.platform:extensions:233.13135.128
  - com.jetbrains.intellij.java:java-frontback-psi:233.13135.128
  - com.jetbrains.intellij.java:java-frontback-psi-impl:233.13135.128
  - com.jetbrains.intellij.java:java-psi:233.13135.128
  - com.jetbrains.intellij.java:java-psi-impl:233.13135.128
  - com.google.guava:failureaccess:1.0.2
  - com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
  - com.google.code.findbugs:jsr305:3.0.2
  - org.checkerframework:checker-qual:3.43.0
  - com.google.errorprone:error_prone_annotations:2.28.0
  - com.google.j2objc:j2objc-annotations:3.0.0
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.20-dev-6663
  - javax.annotation:jsr250-api:1.0
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.20-dev-6663
  - org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.1.20-dev-6663
  - io.vavr:vavr:0.10.4
  - org.jetbrains.kotlin:protobuf-lite:2.6.1-1
  - org.jetbrains.intellij.deps:asm-all:9.0
  - javax.inject:javax.inject:1
  - org.jetbrains:annotations:13.0
  - io.vavr:vavr-match:0.10.4
  - com.jetbrains.intellij.platform:util-jdom:233.13135.128
  - com.jetbrains.intellij.platform:diagnostic:233.13135.128
  - org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm:0.3.7
  - jaxen:jaxen:1.2.0
  - org.jetbrains:annotations:24.0.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.8.0
  - org.slf4j:log4j-over-slf4j:1.7.36
  - net.java.dev.jna:jna-platform:5.13.0
  - oro:oro:2.0.8
  - org.lz4:lz4-java:1.8.0
  - org.apache.commons:commons-compress:1.24.0
  - org.jetbrains.intellij.deps.fastutil:intellij-deps-fastutil:8.5.11-18
  - com.fasterxml:aalto-xml:1.3.2
  - com.jetbrains.intellij.platform:util-trove:233.13135.128
  - org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.8.0
  - org.jetbrains:annotations-java5:24.0.0
  - com.jetbrains.intellij.platform:util-rt-java8:233.13135.128
  - net.java.dev.jna:jna:5.13.0
  - org.codehaus.woodstox:stax2-api:4.2
  - org.jetbrains.intellij.deps:trove4j:1.0.20221201
  - ../../../dependencies/intellij-core
  - ../../cli/cli-base
  - ../../../generators/tree-generator-common
  - ../../../generators
  - ../../fir/tree/tree-generator-fir
  - ../../ir/backend.common
  - ../../../js/js.frontend
  - ..
  - ../../ir/backend.jvm
  - ../../light-classes
  - ../../../wasm/wasm.frontend
  - ../../javac-wrapper
  - ../../frontend.java
  - ../../frontend/cfg
  - ../../cli/cli-common
  - ../../resolution.common
  - ../../util-klib-metadata
  - ../../../native/frontend-native
  - ../../util-klib
  - ../../../core/compiler.common
  - ../../../core/util.runtime
  - ../../backend-common
  - ../../frontend
  - ../../ir/ir.tree
  - ../../util
  - ../../ir/ir.interpreter
  - ../../../js/js.serializer
  - ../../../core/compiler.common.js
  - ../../../js/js.parser
  - ../../../js/js.ast
  - ../../../core/metadata
  - ../../backend
  - ../../backend.common.jvm
  - ../../../analysis/light-classes-base
  - ../../../wasm/wasm.config
  - ../../resolution.common.jvm
  - ../../frontend.common.jvm
  - ../../config.jvm
  - ../../../core/descriptors.jvm
  - ../../../core/descriptors
  - ../../plugin-api
  - ../../../js/js.config
  - ../../../native/utils
  - ../../util-io
  - ../../../libraries/tools/kotlin-annotations-jvm
  - ../../frontend.common-psi
  - ../../psi
  - ../../frontend.common
  - ../../resolution
  - ../../../core/deserialization
  - ../../container
  - org.jetbrains.kotlin:kotlin-script-runtime:2.1.20-dev-6663
  - ../../compiler.version
  - ../../serialization
  - ../../../core/compiler.common.jvm
  - ../../../core/deserialization.common.jvm
  - ../../../core/deserialization.common
  - ../../../core/metadata.jvm
  - ../../fir/cones
  - ../../../core/compiler.common.web

settings:
  kotlin:
    freeCompilerArgs: [-Xjdk-release=, -jvm-target=1.8,-Xjvm-default=all, -Xdont-warn-on-error-suppression, -Xmulti-dollar-interpolation, -Xnon-local-break-continue, -Xskip-prerelease-check, -Xwhen-guards]


test-dependencies:
  - org.jetbrains.kotlin:kotlin-reflect:1.6.10
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.20-dev-6663
  - com.jetbrains.intellij.platform:util:233.13135.128
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.20-dev-6663
  - org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.1.20-dev-6663
  - com.jetbrains.intellij.platform:util-rt:233.13135.128
  - com.jetbrains.intellij.platform:util-base:233.13135.128
  - javax.annotation:jsr250-api:1.0
  - io.vavr:vavr:0.10.4
  - org.jetbrains.kotlin:protobuf-lite:2.6.1-1
  - org.jetbrains:annotations:13.0
  - org.jetbrains.intellij.deps:asm-all:9.0
  - com.google.guava:guava:33.3.1-jre
  - javax.inject:javax.inject:1
  - io.vavr:vavr-match:0.10.4
  - com.google.guava:failureaccess:1.0.2
  - com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
  - com.google.code.findbugs:jsr305:3.0.2
  - org.checkerframework:checker-qual:3.43.0
  - com.google.errorprone:error_prone_annotations:2.28.0
  - com.google.j2objc:j2objc-annotations:3.0.0
  - com.jetbrains.intellij.platform:util-jdom:233.13135.128
  - com.jetbrains.intellij.platform:util-xml-dom:233.13135.128
  - com.jetbrains.intellij.platform:util-class-loader:233.13135.128
  - com.jetbrains.intellij.platform:core:233.13135.128
  - com.jetbrains.intellij.platform:core-impl:233.13135.128
  - com.jetbrains.intellij.platform:extensions:233.13135.128
  - com.jetbrains.intellij.java:java-frontback-psi:233.13135.128
  - com.jetbrains.intellij.java:java-frontback-psi-impl:233.13135.128
  - com.jetbrains.intellij.java:java-psi:233.13135.128
  - com.jetbrains.intellij.java:java-psi-impl:233.13135.128
  - com.jetbrains.intellij.platform:diagnostic:233.13135.128
  - org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm:0.3.7
  - jaxen:jaxen:1.2.0
  - org.jetbrains:annotations:24.0.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.8.0
  - org.slf4j:log4j-over-slf4j:1.7.36
  - net.java.dev.jna:jna-platform:5.13.0
  - oro:oro:2.0.8
  - org.lz4:lz4-java:1.8.0
  - org.apache.commons:commons-compress:1.24.0
  - org.jetbrains.intellij.deps.fastutil:intellij-deps-fastutil:8.5.11-18
  - com.fasterxml:aalto-xml:1.3.2
  - com.jetbrains.intellij.platform:util-trove:233.13135.128
  - org.jetbrains.kotlinx:kotlinx-coroutines-debug:1.8.0
  - org.jetbrains:annotations-java5:24.0.0
  - com.jetbrains.intellij.platform:util-rt-java8:233.13135.128
  - net.java.dev.jna:jna:5.13.0
  - org.codehaus.woodstox:stax2-api:4.2
  - org.jetbrains.intellij.deps:trove4j:1.0.20221201
  - #org.jetbrains.kotlin.kotlin.compiler.config.configuration-keys-generator.main
  - ./../../../generators/tree-generator-common
  - ./../../../generators
  - ./../../fir/tree/tree-generator-fir
  - ./../../cli/cli-base
  - ./../../ir/backend.common
  - ./../../../js/js.frontend
  - ./..
  - ./../../../core/compiler.common
  - ./../../../core/util.runtime
  - ./../../ir/backend.jvm
  - ./../../../wasm/wasm.frontend
  - ./../../light-classes
  - ./../../javac-wrapper
  - ./../../frontend.java
  - ./../../frontend/cfg
  - ./../../cli/cli-common
  - ./../../resolution.common
  - ./../../util-klib-metadata
  - ./../../../native/frontend-native
  - ./../../util-klib
  - ./../../backend-common
  - ./../../frontend
  - ./../../ir/ir.tree
  - ./../../util
  - ./../../ir/ir.interpreter
  - ./../../../js/js.serializer
  - ./../../../core/compiler.common.js
  - ./../../../js/js.parser
  - ./../../../js/js.ast
  - ./../../../core/metadata
  - ./../../../libraries/tools/kotlin-annotations-jvm
  - ./../../backend
  - ./../../backend.common.jvm
  - ./../../../wasm/wasm.config
  - ./../../../analysis/light-classes-base
  - ./../../resolution.common.jvm
  - ./../../frontend.common.jvm
  - ./../../config.jvm
  - ./../../../core/descriptors.jvm
  - ./../../../core/descriptors
  - ./../../plugin-api
  - ./../../../js/js.config
  - ./../../../native/utils
  - ./../../util-io
  - ./../../frontend.common-psi
  - ./../../psi
  - ./../../frontend.common
  - ./../../resolution
  - ./../../../core/deserialization
  - ./../../container
  - org.jetbrains.kotlin:kotlin-script-runtime:2.1.20-dev-6663
  - ./../../compiler.version
  - ./../../serialization
  - ./../../../core/compiler.common.jvm
  - ./../../../core/deserialization.common.jvm
  - ./../../../core/deserialization.common
  - ./../../../core/metadata.jvm
  - ./../../../dependencies/intellij-core
  - ./../../fir/cones
  - ./../../../core/compiler.common.web

test-settings:
  kotlin:
    freeCompilerArgs: [-Xdont-warn-on-error-suppression, -Xmulti-dollar-interpolation, -Xnon-local-break-continue, -opt-in, kotlin.RequiresOptIn, -Xskip-prerelease-check, -Xwhen-guards]
