[versions]
dexMemberList = "4.1.1"
dokka = "2.0.0"
gradle-custom-user-data = "2.0.2"
develocity = "3.18.2"
gradle-plugin-publish = "1.2.1"
# Version for foojay should be also synced with version in repo/gradle-settings-conventions/settings.gradle.kts
gradle-toolchains-foojay-resolver = "0.9.0"
# guava and failureaccess should be aligned relatively
guava = "33.3.1-jre"
failureaccess = "1.0.2"
javaDiffUtils = "4.12"
jdom2 = "2.0.6.1"
kotlinx-serialization = "1.7.3"
# Version of the coroutines should be aligned with the oldest supported IntelliJ IDEA. Intellij IDEA uses 1.6 since 2022.3
# Check the version in this file: https://github.com/JetBrains/intellij-community/blob/cc37866d3827c51712f9856f5e580d405784d1ef/.idea/libraries/kotlinx_coroutines_core.xml
kotlinx-coroutines = "1.8.0"
shadow = "8.3.0" # Should be in sync with version in kotlin-native/
spdx = "0.8.0-dev-14"
proguard = "7.4.2"
ktor = "2.3.13"
kotlinx-metadataJvm = "0.9.0"
kotlinx-bcv = "0.17.0"
gson = "2.11.0"
jetbrains-ideaExt = "1.0.1"
jackson = "2.18.1"
jgit = "7.0.0.202409031743-r"
jsoup = "1.17.2"
junit4 = "4.13.2"
junit5 = "5.10.1"
junit-platform = "1.10.0"
okhttp = "4.12.0"
opentest4j = "1.3.0" # should be consistent with the version brought by junit-platform
android-gradle-plugin = "7.3.1"
android-tools = "30.3.1"
gradle-node-plugin = "7.0.2"
commons-text = "1.10.0"
lincheck = "2.28.1"
xerces = "2.12.2"
caffeine = "2.9.3" # We cannot use the latest version of Caffeine (`3.x`) because it doesn't support Java 8.
compose-stable = "1.7.0-alpha08" # Used for Compose compiler plugin tests
androidx-collections = "1.5.0-alpha02" # Used for Compose compiler plugin tests
ant = "1.10.14"
# It is recommended to skip at least one major release, e.g., use 2.0.21 when the default bootstrap version is 2.2.
# This ensures additional verification that Gradle-related code does not get dependencies of higher LV
kotlin-for-gradle-plugins-compilation = "2.0.21"
intellij-asm = "9.6.1"
diff-utils = "4.12"
opentelemetry-api = "1.41.0"
fastutil = "8.5.13-jb4"
# Wasm specific
wasmedge = "0.14.0"
vavr = "0.10.4"
downloadTask = "5.6.0"
oshi = "6.6.5"
protobuf = "4.28.2"
woodstox-core = "7.1.0"
http-client = "4.5.14"
json = "20231013"
dataframe = "0.14.1"
commons-compress = "1.27.1"
commons-io = "2.18.0"
dataframe-dev = "1.0.0-dev-7243"
org-jetbrains-syntax-api = "0.3.336"
org-jetbrains-annotations = "26.0.2"
schema-kenerator = "2.1.2"

[libraries]
dexMemberList = { module = "com.jakewharton.dex:dex-member-list", version.ref = "dexMemberList" }
dokka-gradlePlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
dokka-versioningPlugin = { module = "org.jetbrains.dokka:versioning-plugin", version.ref = "dokka" }
dokka-multiModulePlugin = { module = "org.jetbrains.dokka:all-modules-page-plugin", version.ref = "dokka" }
downloadTask-gradlePlugin = { module = "de.undercouch:gradle-download-task", version.ref = "downloadTask" }
gradle-customUserData-gradlePlugin = { module = "com.gradle:common-custom-user-data-gradle-plugin", version.ref = "gradle-custom-user-data" }
develocity-gradlePlugin = { module = "com.gradle:develocity-gradle-plugin", version.ref = "develocity" }
gradle-pluginPublish-gradlePlugin = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradle-plugin-publish" }
gradle-toolchainsFoojayResolver-gradlePlugin = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "gradle-toolchains-foojay-resolver" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-metadataJvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "kotlinx-metadataJvm" }
shadow-gradlePlugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
spdx-gradlePlugin = { module = "org.spdx:spdx-gradle-plugin", version.ref = "spdx" }
proguard-gradlePlugin = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard" }
node-gradlePlugin = { module = "com.github.node-gradle:gradle-node-plugin", version.ref = "gradle-node-plugin" }
woodstox-core = { module = "com.fasterxml.woodstox:woodstox-core", version.ref = "woodstox-core" }
dataframe = { module = "org.jetbrains.kotlinx:dataframe", version.ref = "dataframe" }
dataframe-compiler-plugin-core = { module = "org.jetbrains.kotlinx.dataframe:dataframe-compiler-plugin-core", version.ref = "dataframe-dev" }
dataframe-core-dev = { module = "org.jetbrains.kotlinx:dataframe-core", version.ref = "dataframe-dev" }
dataframe-csv-dev = { module = "org.jetbrains.kotlinx:dataframe-csv", version.ref = "dataframe-dev" }

apache-commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
apache-commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
guava-failureaccess = { module = "com.google.guava:failureaccess", version.ref = "failureaccess" }
vavr = { module = "io.vavr:vavr", version.ref = "vavr" }
jetbrains-ideaExt-gradlePlugin = { module = "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext", version.ref = "jetbrains-ideaExt" }
jdom2 = { module = "org.jdom:jdom2", version.ref = "jdom2" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
junit-platform-commons = { module = "org.junit.platform:junit-platform-commons", version.ref = "junit-platform" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite", version.ref = "junit-platform" }
opentest4j = { module = "org.opentest4j:opentest4j", version.ref = "opentest4j" }
lincheck = { module = "org.jetbrains.kotlinx:lincheck", version.ref = "lincheck" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-java-lite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }

android-gradle-plugin-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "android-gradle-plugin" }
android-gradle-plugin-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
android-gradle-plugin-builder = { module = "com.android.tools.build:builder", version.ref = "android-gradle-plugin" }
android-gradle-plugin-builder-model = { module = "com.android.tools.build:builder-model", version.ref = "android-gradle-plugin" }
android-tools-common = { module = "com.android.tools:common", version.ref = "android-tools" }

intellij-fastutil = { module = "org.jetbrains.intellij.deps.fastutil:intellij-deps-fastutil", version.ref = "fastutil" }

xerces = { module = "xerces:xercesImpl", version.ref = "xerces" }

ant = { module = "org.apache.ant:ant", version.ref = "ant" }
intellij-asm = { module = "org.jetbrains.intellij.deps:asm-all", version.ref = "intellij-asm" }
diff-utils = { module = "io.github.java-diff-utils:java-diff-utils", version.ref = "diff-utils" }
okhttp = { module  = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry-api" }

javaDiffUtils = { module = "io.github.java-diff-utils:java-diff-utils", version.ref = "javaDiffUtils" }
kotlinx-bcv = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinx-bcv" }

androidx-collections = { module = "androidx.collection:collection", version.ref = "androidx-collections" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }

org-jetbrains-syntax-api = { module = "org.jetbrains:syntax-api", version.ref = "org-jetbrains-syntax-api" }
org-jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "org-jetbrains-annotations" }

schema-kenerator-core = { module = "io.github.smiley4:schema-kenerator-core", version.ref="schema-kenerator" }
schema-kenerator-serialization = { module = "io.github.smiley4:schema-kenerator-serialization", version.ref="schema-kenerator" }
schema-kenerator-jsonschema = { module = "io.github.smiley4:schema-kenerator-jsonschema", version.ref="schema-kenerator" }

[plugins]
jetbrains-ideaExt = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "jetbrains-ideaExt" }
gradle-node = { id = "com.github.node-gradle.node", version.ref = "gradle-node-plugin" }
kotlinx-bcv = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-bcv" }
